FROM openjdk:11
COPY /var/jenkins_home/workspace/gs-rest-service_main/complete/target/rest-service-complete-0.0.1-SNAPSHOT.jar /usr/src/myapp/
WORKDIR /usr/src/myapp
RUN java -jar rest-service-complete-0.0.1-SNAPSHOT.jar
